/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type UserDto struct {
	// User ID
	Id float64 `json:"id"`
	// The franchise of the user
	Franchise string `json:"franchise"`
	// The display name of the user
	DisplayName string `json:"displayName"`
	// The email address of the user
	Email string `json:"email"`
	// Whether the user must change authenticator
	AuthenticatorMustChange float64 `json:"authenticatorMustChange"`
	// The timestamp when the authenticator was created
	AuthenticatorCreatedTimestamp string `json:"authenticatorCreatedTimestamp"`
	// The timestamp when the user was created
	CreatedTimestamp string `json:"createdTimestamp"`
	// The timestamp when the user logged in last
	LastLoginTimestamp string `json:"lastLoginTimestamp"`
	// The last login type of the user
	LastLoginType string `json:"lastLoginType"`
	// Whether the user is blocked
	Blocked float64 `json:"blocked"`
	// The email status of the user
	EmailStatus string `json:"emailStatus"`
	// Whether the user must change password
	PasswordChangeRequired float64 `json:"passwordChangeRequired"`
	// The access level of the user
	AccessLevel string `json:"accessLevel"`
	// Whether the user is billable
	IsBillable float64 `json:"isBillable"`
	// Whether the user is in testing mode
	IsTestingMode float64 `json:"isTestingMode"`
	// Whether the user is suspended
	IsSuspended float64 `json:"isSuspended"`
	// The language of the user
	Language string `json:"language"`
	// The default infrastructure ID of the user
	InfrastructureIdDefault float64 `json:"infrastructureIdDefault,omitempty"`
	// The GUI settings of the user
	GuiSettings *interface{} `json:"guiSettings"`
	// The promotion tags of the user
	PromotionTags *interface{} `json:"promotionTags"`
	// The experimental tags of the user
	ExperimentalTags *interface{} `json:"experimentalTags"`
	// The custom prices for the user
	CustomPrices *interface{} `json:"customPrices"`
	// The permissions of the user
	Permissions *interface{} `json:"permissions"`
	// The external IDs of the user
	ExternalIds *interface{} `json:"externalIds"`
	// The limits of the user
	Limits *AllOfUserDtoLimits `json:"limits"`
	// Whether the user is excluded from reports
	ExcludeFromReports float64 `json:"excludeFromReports"`
	// Whether the user is a test account
	IsTestAccount float64 `json:"isTestAccount"`
	// The plan type of the user
	PlanType string `json:"planType"`
	// The brand of the user
	Brand string `json:"brand"`
	// Whether the user is a brand manager
	IsBrandManager float64 `json:"isBrandManager"`
	// Whether the user is a datastore publisher
	IsDatastorePublisher float64 `json:"isDatastorePublisher"`
	// The provider of the user
	Provider string `json:"provider"`
	// Whether the user is a archived
	Archived float64 `json:"archived"`
	// The account ID of the user
	AccountId float64 `json:"accountId"`
}
