/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

// The limits the user
type AllOfAccountDtoLimits struct {
	UserResourceServerTypeNameToMaxCount *interface{} `json:"user_resource_server_type_name_to_max_count"`
	WanSubnetPrefixSizeToMaxCount *interface{} `json:"wan_subnet_prefix_size_to_max_count"`
}
