/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type VmDisk struct {
	// VM ID
	Id float64 `json:"id"`
	// VM ID
	VmId float64 `json:"vmId"`
	// Name of the VM Disk datastore
	Datastore string `json:"datastore"`
	// Size of the VM Disk in GB
	SizeGB float64 `json:"sizeGB"`
}
