/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type VmInstance struct {
	// VM Instance ID
	Id float64 `json:"id"`
	// Id of the VM Instance Group.
	GroupId float64 `json:"groupId"`
	// Id of the Infrastructure.
	InfrastructureId float64 `json:"infrastructureId"`
	// Name of the VM Instance.
	Label string `json:"label"`
	// Id of the VM.
	VmId float64 `json:"vmId"`
	// Id of the VM Type.
	TypeId float64 `json:"typeId"`
	// Tags for the VM Instance.
	Tags []string `json:"tags,omitempty"`
	// Service status of the VM Instance.
	ServiceStatus string `json:"serviceStatus"`
	// Id of the VM Instance change object.
	ChangeId float64 `json:"changeId"`
	// Timestamp of the VM Instance creation.
	CreatedTimestamp string `json:"createdTimestamp"`
	// Timestamp of the VM Instance last update.
	UpdatedTimestamp string `json:"updatedTimestamp"`
	// VM Instance change object.
	Operation *interface{} `json:"operation"`
	// Custom variables for the VM Instance.
	CustomVariables *interface{} `json:"customVariables,omitempty"`
	// Disk size in GB of the VM Instance.
	DiskSizeGB float64 `json:"diskSizeGB"`
	// Id of the template used by the VM Instance.
	TemplateIdOrigin float64 `json:"templateIdOrigin,omitempty"`
	// Id of the VM Pool.
	VmPoolId float64 `json:"vmPoolId,omitempty"`
}
