/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type StorageRegistrationResponseJobInfo struct {
	AfcId float64 `json:"afcId,omitempty" yaml:"afcId,omitempty"`
	AfcGroupId float64 `json:"afcGroupId,omitempty" yaml:"afcGroupId,omitempty"`
}
