/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type AfcJobInfo struct {
	// The id of the afc job.
	AfcId float64 `json:"afcId"`
	// The id of the afc job group.
	AfcGroupId float64 `json:"afcGroupId"`
}
