/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type UserExperimentalTagDto struct {
	// The experimental tag for the user
	ExperimentalTag string `json:"experimentalTag,omitempty" yaml:"experimentalTag,omitempty"`
	// Whether to remove the experimental tag
	RemoveExperimentalTag bool `json:"removeExperimentalTag,omitempty" yaml:"removeExperimentalTag,omitempty"`
}
