/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ResourcePoolWithStatsDto struct {
	// Resource Pool ID
	ResourcePoolId float64 `json:"resource_pool_id"`
	// Label of the Resource Pool
	ResourcePoolLabel string `json:"resource_pool_label"`
	// Description of the Resource Pool
	ResourcePoolDescription string `json:"resource_pool_description"`
	// Resource Pool Created Timestamp
	ResourcePoolCreatedTimestamp string `json:"resource_pool_created_timestamp"`
	// Resource Pool Updated Timestamp
	ResourcePoolUpdatedTimestamp string `json:"resource_pool_updated_timestamp"`
	// Resource Pool statistics for users, servers, and subnet pools
	Statistics *AllOfResourcePoolWithStatsDtoStatistics `json:"statistics"`
}
