/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ServerVncInfoDto struct {
	// Active VNC sessions
	ActiveSessions float64 `json:"activeSessions" yaml:"activeSessions"`
	// Max active VNC sessions
	MaxSessions float64 `json:"maxSessions" yaml:"maxSessions"`
	// VNC port
	Port float64 `json:"port" yaml:"port"`
	// VNC timeout
	Timeout float64 `json:"timeout" yaml:"timeout"`
	// VNC enabled
	Enable string `json:"enable" yaml:"enable"`
}
