/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionInstanceArray struct {
	// Label of the instance array.
	Label string `json:"label" yaml:"label"`
	// Instance count value or reference to variable.
	InstanceCount string `json:"instanceCount" yaml:"instanceCount"`
	// Server type variable reference.
	ServerType string `json:"serverType" yaml:"serverType"`
	// OS template variable reference.
	OsTemplate string `json:"osTemplate" yaml:"osTemplate"`
	// Connected shared drive arrays.
	ConnectedSharedDrives []string `json:"connectedSharedDrives,omitempty" yaml:"connectedSharedDrives,omitempty"`
	// Custom variables. The value may be a reference to an input variable.
	CustomVariables []CustomVariable `json:"customVariables,omitempty" yaml:"customVariables,omitempty"`
	// Labels of instance arrays this one depends on.
	Dependencies []string `json:"dependencies,omitempty" yaml:"dependencies,omitempty"`
}
