/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type AiGenerateRequestDto struct {
	// Datacenter that is being filtered
	Datacenter string `json:"datacenter" yaml:"datacenter"`
	// String input sent to the AI
	Prompt string `json:"prompt" yaml:"prompt"`
}
