/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type NetworkEquipmentReProvisionOptions struct {
	NetworkEquipmentId float64 `json:"networkEquipmentId" yaml:"networkEquipmentId"`
	ReprovisionType string `json:"reprovisionType" yaml:"reprovisionType"`
}
