/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

// The new password of the user
type AllOfUpdateUserDtoPassword struct {
	// The new password of the user
	NewPassword string `json:"newPassword"`
	// The old password of the user
	OldPassword string `json:"oldPassword,omitempty"`
}
