/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type BucketHostsModifyBulk struct {
	// List of operations to be performed on the File Share Hosts
	BucketHostBulkOperations []BucketHostBulkOperation `json:"bucketHostBulkOperations"`
}
