/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionInputInteger struct {
	// Minimum allowed value.
	MinValue int32 `json:"minValue,omitempty" yaml:"minValue,omitempty"`
	// Maximum allowed value.
	MaxValue int32 `json:"maxValue,omitempty" yaml:"maxValue,omitempty"`
	// Denied values.
	DeniedValues []int32 `json:"deniedValues,omitempty" yaml:"deniedValues,omitempty"`
	// Default value.
	DefaultValue int32 `json:"defaultValue,omitempty" yaml:"defaultValue,omitempty"`
}
