/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type TaskDto struct {
	// Run an Ansible task.
	RunAnsibleTask *AllOfTaskDtoRunAnsibleTask `json:"run_ansible_task,omitempty" yaml:"run_ansible_task,omitempty"`
	// Run a webhook task.
	RunWebhook *AllOfTaskDtoRunWebhook `json:"run_webhook,omitempty" yaml:"run_webhook,omitempty"`
}
