/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionDefinitionDto struct {
	// The kind of extension.
	Kind string `json:"kind" yaml:"kind"`
	// Schema version of the extension.
	SchemaVersion string `json:"schema_version" yaml:"schema_version"`
	// Name of the extension.
	Name string `json:"name" yaml:"name"`
	// Label of the extension.
	Label string `json:"label,omitempty" yaml:"label,omitempty"`
	// Type of the extension.
	Type_ string `json:"type" yaml:"type"`
	// Vendor of the extension.
	Vendor string `json:"vendor" yaml:"vendor"`
	// Version of the extension.
	ExtensionVersion string `json:"extension_version" yaml:"extension_version"`
	// Description of the extension.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// Icon of the extension.
	Icon string `json:"icon" yaml:"icon"`
	// List of dependencies for the extension.
	Dependencies []DependencyDto `json:"dependencies" yaml:"dependencies"`
	// Platform service information for the extension.
	PlatformService *AllOfExtensionDefinitionDtoPlatformService `json:"platform_service" yaml:"platform_service"`
}
