/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionTaskWebhook struct {
	// Webhook task endpoint.
	Endpoint string `json:"endpoint,omitempty" yaml:"endpoint,omitempty"`
	// Webhook task request body template.
	RequestTemplate string `json:"requestTemplate,omitempty" yaml:"requestTemplate,omitempty"`
}
