/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type UserSuspendDto struct {
	// The suspend reason of the user
	SuspendReason string `json:"suspendReason,omitempty" yaml:"suspendReason,omitempty"`
	// The public comment for the suspension
	SuspendReasonPublicComment string `json:"suspendReasonPublicComment,omitempty" yaml:"suspendReasonPublicComment,omitempty"`
	// The private comment for the suspension
	SuspendReasonPrivateComment string `json:"suspendReasonPrivateComment,omitempty" yaml:"suspendReasonPrivateComment,omitempty"`
	// Whether to remove the suspension
	RemoveSuspension bool `json:"removeSuspension,omitempty" yaml:"removeSuspension,omitempty"`
}
