/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type OutputDto struct {
	// Controller URL for the output.
	ControllerUrl string `json:"controller_url" yaml:"controller_url"`
	// Type of the output.
	Type_ string `json:"type" yaml:"type"`
	// Name of the output.
	Name string `json:"name" yaml:"name"`
	// Template of the output.
	Template string `json:"template" yaml:"template"`
}
