/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type InfrastructureRequirementDto struct {
	// Instance array details for the infrastructure requirement.
	InstanceArray *AllOfInfrastructureRequirementDtoInstanceArray `json:"instance_array,omitempty" yaml:"instance_array,omitempty"`
	// Shared drive array details for the infrastructure requirement.
	SharedDriveArray *AllOfInfrastructureRequirementDtoSharedDriveArray `json:"shared_drive_array,omitempty" yaml:"shared_drive_array,omitempty"`
}
