/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type CreateExtensionDto struct {
	// The extension name
	Name string `json:"name" yaml:"name"`
	// The extension unique label
	Label string `json:"label,omitempty" yaml:"label,omitempty"`
	// The extension description
	Description string `json:"description" yaml:"description"`
	// Extension definition (JSON)
	Definition *interface{} `json:"definition" yaml:"definition"`
}
