/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionTask struct {
	// Label of the task.
	Label string `json:"label" yaml:"label"`
	// Type of the task.
	TaskType string `json:"taskType" yaml:"taskType"`
	// Task options.
	Options *OneOfExtensionTaskOptions `json:"options" yaml:"options"`
}
