/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionDto struct {
	// The extension ID
	Id float64 `json:"id"`
	// The extension unique slug
	Slug string `json:"slug,omitempty"`
	// The extension name
	Name string `json:"name"`
	// The extension unique label
	Label string `json:"label,omitempty"`
	// The extension description
	Description string `json:"description"`
	// Extension status
	Status string `json:"status"`
	// Extension definition (JSON)
	Definition string `json:"definition"`
	Version string `json:"version,omitempty"`
}
