/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionInfoDto struct {
	// The extension ID
	Id float64 `json:"id,omitempty" yaml:"id,omitempty"`
	// The extension unique slug
	Slug string `json:"slug,omitempty" yaml:"slug,omitempty"`
	// The extension name
	Name string `json:"name,omitempty" yaml:"name,omitempty"`
	// The extension unique label
	Label string `json:"label,omitempty" yaml:"label,omitempty"`
	// The extension description
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// Extension status
	Status string `json:"status,omitempty" yaml:"status,omitempty"`
	// Icon of the extension.
	Icon string `json:"icon,omitempty" yaml:"icon,omitempty"`
}
