/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type OneOfExtensionInputOptions struct {
    ExtensionInputString `yaml:",inline"`
    ExtensionInputInteger `yaml:",inline"`
    ExtensionInputServerType `yaml:",inline"`
    ExtensionInputOsTemplate `yaml:",inline"`
    ExtensionInputBoolean `yaml:",inline"`
}
