/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ResourcePoolDto struct {
	// Resource Pool ID
	ResourcePoolId float64 `json:"resource_pool_id"`
	// Label of the Resource Pool
	ResourcePoolLabel string `json:"resource_pool_label"`
	// Description of the Resource Pool
	ResourcePoolDescription string `json:"resource_pool_description"`
}
