/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type UpdateFileShare struct {
	// Disk size in GB for File Share
	SizeGB float64 `json:"sizeGB,omitempty" yaml:"sizeGB,omitempty"`
	// Label of the File Share.
	Label string `json:"label,omitempty" yaml:"label,omitempty"`
	GuiSettings *GenericGuiSettings `json:"guiSettings,omitempty" yaml:"guiSettings,omitempty"`
}
