/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type UpdateUserDto struct {
	// The new display name of the user
	DisplayName string `json:"displayName,omitempty"`
	// The new password of the user
	Password *AllOfUpdateUserDtoPassword `json:"password,omitempty"`
	// The new login e-mail of the user
	Email string `json:"email,omitempty"`
	// The redirect URL for the user
	RedirectUrl string `json:"redirectUrl,omitempty"`
	// The AES key for the user
	AESKey string `json:"AESKey,omitempty"`
	// The new e-mail status of the user
	EmailStatus string `json:"emailStatus,omitempty"`
	// The new language of the user
	Language string `json:"language,omitempty"`
	// The new brand of the user
	Brand string `json:"brand,omitempty"`
	// The new brand manager status of the user
	IsBrandManager bool `json:"isBrandManager,omitempty"`
	// The new user delegates of the user.
	Delegates []UserDelegateDto `json:"delegates,omitempty"`
	// The new blocked status of the user
	IsBlocked bool `json:"isBlocked,omitempty"`
	// The new suspension status of the user
	Suspension *AllOfUpdateUserDtoSuspension `json:"suspension,omitempty"`
	// The new access level of the user
	AccessLevel string `json:"accessLevel,omitempty"`
	// The new promotions of the user.
	Promotions []UserPromotionDto `json:"promotions,omitempty"`
	// The new experimental tags of the user.
	ExperimentalTags []UserExperimentalTagDto `json:"experimentalTags,omitempty"`
	// The new custom prices of the user
	CustomPrices *interface{} `json:"customPrices,omitempty"`
	// The new permissions of the user.
	Permissions *AllOfUpdateUserDtoPermissions `json:"permissions,omitempty"`
	// Whether the user account is a test one.
	IsTestAccount bool `json:"isTestAccount,omitempty"`
	// Whether the user account is billable.
	IsBillable bool `json:"isBillable,omitempty"`
}
