/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type VmDto struct {
	// VM ID
	Id float64 `json:"id"`
	// Name of the VM
	Name string `json:"name"`
	// Id of the site for the VM
	SiteId float64 `json:"siteId"`
	// Datacenter of the VM
	DatacenterName string `json:"datacenterName"`
	// ID of the infrastructure where this VM is deployed
	InfrastructureId float64 `json:"infrastructureId"`
	// ID of the user that owns this VM
	UserId float64 `json:"userId"`
	// Email of the user that owns this VM
	UserEmail string `json:"userEmail"`
	// ID of the instance where this VM is deployed
	InstanceId float64 `json:"instanceId"`
	// ID of the VM instance where this VM is deployed
	VmInstanceId float64 `json:"vmInstanceId"`
	// Name of the host
	Host string `json:"host"`
	// List of hosts
	Hosts []string `json:"hosts"`
	// Number of CPU cores for the VM
	CpuCores float64 `json:"cpuCores"`
	// RAM in GB for the VM
	RamGB float64 `json:"ramGB"`
	// Disk size in GB for the VM
	DiskSizeGB float64 `json:"diskSizeGB"`
	// The id of the VM Type. This is a number.
	TypeId float64 `json:"typeId"`
	// The id of the VM Pool. This is a number.
	PoolId float64 `json:"poolId"`
	// The administration state of the VM.
	AdministrationState *interface{} `json:"administrationState"`
	// VM comments.
	Comments float64 `json:"comments"`
	// The power state of the VM.
	PowerState *interface{} `json:"powerState"`
	// Timestamp when the VM power state was last updated.
	PowerStateLastUpdatedTimestamp string `json:"powerStateLastUpdatedTimestamp"`
	// Timestamp when the VM was created
	CreatedTimestamp string `json:"createdTimestamp"`
	// Timestamp when the VM was allocated
	AllocationTimestamp string `json:"allocationTimestamp"`
	// Tags for the VM.
	Tags []string `json:"tags"`
	// The port number for the VNC server.
	VncPort float64 `json:"vncPort"`
	// The password for the VNC server.
	VncPassword string `json:"vncPassword"`
	// The disks of the VM.
	Disks []VmDiskDto `json:"disks"`
}
