/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type UpdateVmPoolClusterHostInterface struct {
	// Fabric of the switch interface
	Fabric string `json:"fabric,omitempty" yaml:"fabric,omitempty"`
	// Id of the switch
	SwitchId float64 `json:"switchId,omitempty" yaml:"switchId,omitempty"`
	// Name of the switch interface
	SwitchInterfaceName float64 `json:"switchInterfaceName,omitempty" yaml:"switchInterfaceName,omitempty"`
}
