/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type BucketExtendedInfo struct {
	// Id of the Bucket
	Id float64 `json:"id,omitempty" yaml:"id,omitempty"`
	// Change id of the Bucket
	ChangeId float64 `json:"changeId,omitempty" yaml:"changeId,omitempty"`
	// Infrastructure id of the Bucket
	InfrastructureId float64 `json:"infrastructureId,omitempty" yaml:"infrastructureId,omitempty"`
	// Disk size in GB for Bucket
	SizeGB float64 `json:"sizeGB,omitempty" yaml:"sizeGB,omitempty"`
	// Timestamp of the Bucket creation.
	CreatedTimestamp string `json:"createdTimestamp,omitempty" yaml:"createdTimestamp,omitempty"`
	// Timestamp of the Bucket last update.
	UpdatedTimestamp string `json:"updatedTimestamp,omitempty" yaml:"updatedTimestamp,omitempty"`
	// Id of the storage pool the Bucket is assigned to
	StoragePoolId float64 `json:"storagePoolId,omitempty" yaml:"storagePoolId,omitempty"`
	// Service status of the Bucket
	ServiceStatus string `json:"serviceStatus,omitempty" yaml:"serviceStatus,omitempty"`
	// Label of the Bucket.
	Label string `json:"label,omitempty" yaml:"label,omitempty"`
	// Subdomain of the Bucket.
	Subdomain string `json:"subdomain,omitempty" yaml:"subdomain,omitempty"`
	// Subdomain permanent of the Bucket.
	SubdomainPermanent string `json:"subdomainPermanent,omitempty" yaml:"subdomainPermanent,omitempty"`
	// Id of the DNS subdomain for the Bucket.
	DnsSubdomainId float64 `json:"dnsSubdomainId,omitempty" yaml:"dnsSubdomainId,omitempty"`
	// Id of the VLAN for the Bucket.
	NetworkVlanId float64 `json:"networkVlanId,omitempty" yaml:"networkVlanId,omitempty"`
	// GUI settings for the Bucket. This is a JSON object.
	GuiSettings *AllOfBucketExtendedInfoGuiSettings `json:"guiSettings,omitempty" yaml:"guiSettings,omitempty"`
	// Endpoint of the Bucket.
	Endpoint string `json:"endpoint,omitempty" yaml:"endpoint,omitempty"`
	// Endpoint of the Bucket.
	AccessKeyId string `json:"accessKeyId,omitempty" yaml:"accessKeyId,omitempty"`
	// Endpoint of the Bucket.
	SecretKeyEncrypted string `json:"secretKeyEncrypted,omitempty" yaml:"secretKeyEncrypted,omitempty"`
	// Infrastructure information
	Infrastructure *interface{} `json:"infrastructure" yaml:"infrastructure"`
	Links *interface{} `json:"links,omitempty" yaml:"links,omitempty"`
}
