/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type UpdateExtensionDto struct {
	// The extension name
	Name string `json:"name,omitempty"`
	// The extension unique label
	Label string `json:"label,omitempty"`
	// The extension description
	Description string `json:"description,omitempty"`
	// Extension definition (JSON)
	Definition string `json:"definition,omitempty"`
}
