/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

// Shared drive array details for the infrastructure requirement.
type AllOfInfrastructureRequirementDtoSharedDriveArray struct {
	// Label of the shared drive array.
	Label string `json:"label" yaml:"label"`
	// Minimum size of the shared drive array.
	MinSize string `json:"min_size" yaml:"min_size"`
}
