/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionInputOsTemplate struct {
	// OS family type.
	OsFamily string `json:"osFamily,omitempty" yaml:"osFamily,omitempty"`
}
