/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type Server struct {
	ServerId float64 `json:"serverId"`
	ServerTypeId float64 `json:"serverTypeId"`
	DatacenterName string `json:"datacenterName"`
	ServerUUID string `json:"serverUUID"`
	SerialNumber string `json:"serialNumber,omitempty"`
	ManagementAddress string `json:"managementAddress"`
	Username string `json:"username"`
	PasswordEncrypted string `json:"passwordEncrypted"`
	ImpiVersion string `json:"impiVersion,omitempty"`
	RamGbytes float64 `json:"ramGbytes"`
	ProcessorCount float64 `json:"processorCount"`
	ProcessorCoreMhz float64 `json:"processorCoreMhz"`
	ProcessorCoreCount float64 `json:"processorCoreCount"`
	ProcessorName string `json:"processorName,omitempty"`
	ProcessorCpuMark float64 `json:"processorCpuMark,omitempty"`
	ProcessorThreads float64 `json:"processorThreads,omitempty"`
	DiskCount float64 `json:"diskCount"`
	MgmtSnmpPort float64 `json:"mgmtSnmpPort,omitempty"`
	MgmtSnmpPasswordEncrypted string `json:"mgmtSnmpPasswordEncrypted,omitempty"`
	BmcMacAddress string `json:"bmcMacAddress,omitempty"`
	ServerMetricsMetadata *interface{} `json:"serverMetricsMetadata"`
	Vendor string `json:"vendor,omitempty"`
	VendorSkuId string `json:"vendorSkuId,omitempty"`
	Model string `json:"model,omitempty"`
	VncPort float64 `json:"vncPort,omitempty"`
	VncPasswordEncrypted float64 `json:"vncPasswordEncrypted,omitempty"`
	IsBasicCampusEndpoint float64 `json:"isBasicCampusEndpoint"`
	ServerCleanupPolicyId float64 `json:"serverCleanupPolicyId,omitempty"`
	RequiresReRegister float64 `json:"requiresReRegister"`
	ServerSupportsSol float64 `json:"serverSupportsSol"`
	ServerSupportsVirtualMedia float64 `json:"serverSupportsVirtualMedia"`
	ServerSupportsOobProvisioning float64 `json:"serverSupportsOobProvisioning"`
	BiosInfo *interface{} `json:"biosInfo,omitempty"`
	VendorInfo *interface{} `json:"vendorInfo,omitempty"`
	ServerClass string `json:"serverClass"`
	ServerStatus string `json:"serverStatus"`
	ServerComments string `json:"serverComments,omitempty"`
	ServerCapacityMbps float64 `json:"serverCapacityMbps,omitempty"`
	ServerDiskWipe float64 `json:"serverDiskWipe"`
	ServerDiskCount float64 `json:"serverDiskCount,omitempty"`
	AdministrationState string `json:"administrationState"`
	ServerDhcpStatus string `json:"serverDhcpStatus"`
	GpuCount float64 `json:"gpuCount"`
	GpuInfo []interface{} `json:"gpuInfo"`
	Submodel string `json:"submodel,omitempty"`
	SupportsFcProvisioning float64 `json:"supportsFcProvisioning"`
	BootLastUpdateTimestamp string `json:"bootLastUpdateTimestamp,omitempty"`
	RegisteredTimestamp string `json:"registeredTimestamp,omitempty"`
	ServerCreatedTimestamp string `json:"serverCreatedTimestamp"`
	PowerStatus string `json:"powerStatus"`
	PowerStatusLastUpdateTimestamp string `json:"powerStatusLastUpdateTimestamp"`
}
