/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionDependency struct {
	// Metalsoft Controller version required by the extension.
	ControllerVersion string `json:"controllerVersion" yaml:"controllerVersion"`
	// List of OS templates required by the extension.
	OsTemplates []string `json:"osTemplates" yaml:"osTemplates"`
}
