/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionTaskType string

// List of ExtensionTaskType
const (
	EXTENSION_TASK_ANSIBLE_ExtensionTaskType ExtensionTaskType = "ExtensionTaskAnsible"
	EXTENSION_TASK_WEBHOOK_ExtensionTaskType ExtensionTaskType = "ExtensionTaskWebhook"
)
