/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type UpdateBucket struct {
	// Disk size in GB for Bucket
	SizeGB float64 `json:"sizeGB,omitempty" yaml:"sizeGB,omitempty"`
	// Label of the Bucket.
	Label string `json:"label,omitempty" yaml:"label,omitempty"`
	// Settings for GUI. In JSON format
	GuiSettings *AllOfUpdateBucketGuiSettings `json:"guiSettings,omitempty" yaml:"guiSettings,omitempty"`
}
