/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionActions struct {
	// Pre-deploy tasks.
	PreDeploy []ExtensionTask `json:"preDeploy,omitempty" yaml:"preDeploy,omitempty"`
	// Post-deploy tasks.
	PostDeploy []ExtensionTask `json:"postDeploy,omitempty" yaml:"postDeploy,omitempty"`
}
