/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type UpdateAccountDto struct {
	// The ID of the parent account
	ParentAccountId float64 `json:"parentAccountId,omitempty"`
	// The name of the account
	Name string `json:"name,omitempty"`
	// The code of the account
	Code string `json:"code,omitempty"`
	// The fiscal number of the account
	FiscalNumber string `json:"fiscalNumber,omitempty"`
	// The address of the account
	Address *AllOfUpdateAccountDtoAddress `json:"address,omitempty"`
	// The user ID of the primary contact
	PrimaryContactId float64 `json:"primaryContactId,omitempty"`
	// The user ID of the secondary contact
	SecondaryContactId float64 `json:"secondaryContactId,omitempty"`
}
