/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionInfrastructure struct {
	// Instance array details for the infrastructure requirement.
	InstanceArrays []ExtensionInstanceArray `json:"instanceArrays,omitempty" yaml:"instanceArrays,omitempty"`
	// Shared drive details for the infrastructure requirement.
	SharedDrives []ExtensionSharedDrive `json:"sharedDrives,omitempty" yaml:"sharedDrives,omitempty"`
}
