/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type InputDto struct {
	// Label of the input.
	Label string `json:"label" yaml:"label"`
	// Type of the input.
	Type_ string `json:"type" yaml:"type"`
	// Name of the input.
	Name string `json:"name" yaml:"name"`
	// Validation regex pattern for the input.
	ValidationRegexp string `json:"validation_regexp,omitempty" yaml:"validation_regexp,omitempty"`
}
