/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type FileShareStorageInfo struct {
	// Id of the File Share
	Id float64 `json:"id,omitempty"`
	// Change id of the File Share
	ChangeId float64 `json:"changeId,omitempty"`
	// Infrastructure id of the File Share
	InfrastructureId float64 `json:"infrastructureId,omitempty"`
	// Disk size in GB for File Share
	SizeGB float64 `json:"sizeGB,omitempty"`
	// Timestamp of the File Share creation.
	CreatedTimestamp string `json:"createdTimestamp,omitempty"`
	// Timestamp of the File Share last update.
	UpdatedTimestamp string `json:"updatedTimestamp,omitempty"`
	// Id of the storage pool the File Share is assigned to
	StoragePoolId float64 `json:"storagePoolId,omitempty"`
	// Service status of the File Share
	ServiceStatus string `json:"serviceStatus,omitempty"`
	// Label of the File Share.
	Label string `json:"label,omitempty"`
	// Subdomain of the File Share.
	Subdomain string `json:"subdomain,omitempty"`
	// Subdomain permanent of the File Share.
	SubdomainPermanent string `json:"subdomainPermanent,omitempty"`
	// Id of the DNS subdomain for the File Share.
	DnsSubdomainId float64 `json:"dnsSubdomainId,omitempty"`
	// Id of the VLAN for the File Share.
	NetworkVlanId float64 `json:"networkVlanId,omitempty"`
	// GUI settings for the File Share. This is a JSON object.
	GuiSettings *AllOfFileShareStorageInfoGuiSettings `json:"guiSettings,omitempty"`
	// Endpoint of the File Share.
	Endpoint string `json:"endpoint,omitempty"`
	// Infrastructure information
	Infrastructure *interface{} `json:"infrastructure"`
}
