/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ExtensionAsset struct {
	// Label of the asset.
	Label string `json:"label" yaml:"label"`
	// Name of the asset.
	Name string `json:"name" yaml:"name"`
	// Type of the asset.
	AssetType string `json:"assetType" yaml:"assetType"`
	// URL of the asset.
	Url string `json:"url" yaml:"url"`
	// Required assets by this asset.
	RequiredAssets []string `json:"requiredAssets,omitempty" yaml:"requiredAssets,omitempty"`
}
