/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type UpdateVm struct {
	// VM comments.
	Comments float64 `json:"comments,omitempty"`
	// Tags for the VM. This is a JSON object.
	Tags []string `json:"tags,omitempty"`
}
