/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type ServerPowerSetDto struct {
	// The power state of the server
	PowerCommand string `json:"powerCommand" yaml:"powerCommand"`
}
