/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

type AiGenerateResponseDto struct {
	// Response to the question asked by the user
	Result string `json:"result"`
	// Steps to be taken to achieve the result
	Steps string `json:"steps"`
}
