/*
 * MetalSoft REST API
 *
 * MetalSoft REST API documentation
 *
 * API version: 2.0
 * Contact: support@metalsoft.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sdk2

// The job info of the server.
type AllOfServerRegistrationResponseDtoJobInfo struct {
	// The id of the afc job.
	AfcId float64 `json:"afcId" yaml:"afcId"`
	// The id of the afc job group.
	AfcGroupId float64 `json:"afcGroupId" yaml:"afcGroupId"`
}
